### ISSUE TITLE
Demo files not working as expected. 

### ISSUE THREAD

**Issue by bharat15-ml** [scholzj/demo-kafka-strimzi-telegram-ml#13]
Hi @scholzj, 

I really need your help to re-run this demo. I am planning to run this demo with strimzi-operator 0.34.0. 

Till deployments of 01-kafka.yaml, 02-kafka-connect.yaml, 03-telegram-source.yaml, 04-telegram-sink.yaml with slight updates in apiVersion worked fine. 

I have rebuilt connect docker image with the below dockerfile and the deployments working fine.

    FROM quay.io/strimzi/kafka:0.34.0-kafka-3.4.0
    USER root:root
    RUN mkdir -P /opt/kafka/plugins/camel
    COPY ./camel-telegram-kafka-connector-0.11.5-package.tar.gz /opt/kafka/plugins/camel/
    RUN tar -zxvf /opt/kafka/plugins/camel/camel-telegram-kafka-connector-0.11.5-package.tar.gz --directory /opt/kafka/plugins/camel/
    RUN rm /opt/kafka/plugins/camel/camel-telegram-kafka-connector-0.11.5-package.tar.gz 
    USER 1001

I am facing an issue with these deployments, where it is failing, and deployments went into crashLoopBackOff state.

**05-telegram-transformer.yaml**   This file deployment is failing with the below error - 

    ERROR KafkaStreams: 443 - stream-client [ telegram-transformer-*] all stream threads have died. the instance will be in 
    error state and should be closed.

    Exception in thread "telegram-transformer-*" org.apache.kafka.streams.errors.StreamsException: Exception caught in 
    process. taskID=0_0, processor=KSTREAM_SOURCE-0000000000, topic=telegram-inbox, partition=0, offset=0, 
    stacktrace=java.lang.NullPointerException

        at cz.scholz.demo.telegram.transformer.TelegramTransformer.lambda$main$0(TelegramTransformer.java:43)

**06-sentiment-analysis.yaml**,  This deployment is failing with error - 

    java: symbol lookup error: /tmp/.djl.ai/pytorch/.pytorch/cache/1.6.0-2020828cpu-linux-x86_64/0.7.0-SNAPSHOT- 20200903cpulibdjl_torch.so:undefinedsymbol:_ZN5torch3jit4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3c108optionalINS9_6DeviceEEERSt13unordered_mapIS6_S6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIS7_S6_EEE

**07-object-detection.yaml**, This deployment is failing with error - 

    ERROR KafkaStreams: 443 - stream-client [ object-detection-*] all stream threads have died. the instance will be in 
    error state and should be closed.

Could you please check and help with this? Thanks for your time!!

**Comment by scholzj** [comment]
I used this demo with Strimzi 0.20 (which was roughly 3 years ago). Feel free to use it as inspiration, but I cannot guarantee if or how will it work 3 years later. Sorry.
